-- Types.lua
---@alias ScreenState "rocks" | "upgrades" | "museum"
---@alias RockType "rock1" | "rock2" | "rock3"
---@alias ValuableType "Diamond" | "Topaz" | "Coal" | "Emerald" | "Ruby"
---@alias CollectableType "Boot" | "Bone" | "Ring"
---@alias DropValuesKvPs {valuableType: ValuableType, chance: number}
---@alias RockScreenState {rockAsNumberOnScreen: number}
---@alias GameContext {screenState: ScreenState, rockScreenState: RockScreenState, screenW: number, screenH: number}
---@alias RockSprite {w: number, h: number, x: number, y: number}
---@alias RockGeneric { health: number, rockType: RockType, rockTypeNumber: number, sprite: RockSprite, active: boolean, dropTable: DropValuesKvPs[]}
---@alias PlayerLevels {strength_level: number, heatsinks_level: number, drop_chances_level: number, ore_value_level: number}
---@alias DropChanceMult {coal_mult: number, topaz_mult: number, diamond_mult: number, emerald_mult: number, ruby_mult: number, collectable_mult: number}
---@alias UpgradeMultipliers {strength_mult: number, heatsinks_mult: number, drop_chances_mult: DropChanceMult, ore_value_mult: number}
---@alias RewardInfo {valuableType: ValuableType, value: number}
---@alias RewardTable DropValuesKvPs[]
---@alias Collectable {collectableType: CollectableType, value: number, chance: number}
---@alias CollectableList {RockType: Collectable[]}
